### ISSUE TITLE
What injection/build.

### ISSUE THREAD

**Issue by Dufiw** [T1GxR/Axion-CS2-RAGE-CHEAT#1]
I've tried debug build and tried injecting with manual map & loadlibrary but both just crash.

What injector did you use? or Build version

Injectors used 'TheKruz' but modified and 'Extreme Injector' default

here's the SS of where is crashes I'll try to fix but 🤷  Edit: Fixed
![image](https://github.com/T1GxR/Axion-CS2-RAGE-CHEAT/assets/121215919/a1717526-2493-42f8-8a1c-44311320e3e6)

**Comment by T1GxR** [comment]
You should use release x64 when building and it should work if you successfully updated all the stuff inside the code.

**Comment by Dufiw** [comment]
> You should use release x64 when building and it should work if you successfully updated all the stuff inside the code.

Yea, I'm updating things now I'm trying to get the updated sig for 'MATERIAL_SYSTEM2_DLL' because the current is outdated/not working

**Comment by Dufiw** [comment]
`memory.cpp:370 "48 89 5C 24 00 48 89 6C 24 00 56 57 41 56 48 81 EC 00 00 00 00 48 8D 0D"`


haven't found the new one yet but here is where my crash is being called.

**Comment by Dufiw** [comment]
here what i got to show up so far in console. only updated a few sigs that I could.

but after saying 'found 256' it crashes 🤷 
![image](https://github.com/T1GxR/Axion-CS2-RAGE-CHEAT/assets/121215919/066ddfd5-0d4f-4289-86d5-1621f2f5e5cc)

**Comment by T1GxR** [comment]
> here what i got to show up so far in console. only updated a few sigs that I could.
> 
> but after saying 'found 256' it crashes 🤷 ![image](https://private-user-images.githubusercontent.com/121215919/322313360-066ddfd5-0d4f-4289-86d5-1621f2f5e5cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODM1NjAsIm5iZiI6MTcxMzk4MzI2MCwicGF0aCI6Ii8xMjEyMTU5MTkvMzIyMzEzMzYwLTA2NmRkZmQ1LTBkNGYtNDI4OS04NmQ1LTE2MjFmMmY1ZTVjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxODI3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWU1MTQ1ZjJiZGU4MTY3ZWMzMWNlMmNjZTg5YWJhNWE4YWI1M2IxMzFlM2QyNzJlMTg1MTY4ZDQzNTc1NTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9bFcHQyIpmuHtkvysjmcXxVUGbThQS4LS1Jn523ny_0)

build on publish and it should work, or at least will tell you the errors you have to fix!
