### ISSUE TITLE
What 2 change?

### ISSUE THREAD

**Issue by MattPlayGamez** [T1GxR/Axion-CS2-RAGE-CHEAT#15]
Hi there,
Which files should I change. Only copying the hooks.cpp and hooks.h files from asphyxia doesn't solve my issue.
Can someone tell me what I need to move in total or give me their source, please.
I've been reading the other "issues" but I don't know which lines to change as they do not correspond to each other. (Axion vs asphyxia) (hooks.cpp). I see the CS_XOR but don't know which one I should take from asphyxia

Kind Regards,
Matt

**Comment by RtlSecureZeroMemory** [comment]
you better dont waste your time with asphyxia or axion, because you need custom (self made) injector to make it run.(witb bypassing)

**Comment by MattPlayGamez** [comment]
Ok thanks for responding!

**Comment by weedptr** [comment]
> you better dont waste your time with asphyxia or axion, because you need custom (self made) injector to make it run.(witb bypassing)

u dont need to... just use any load lib inj...
