### ISSUE TITLE
where to input offset?

### ISSUE THREAD

**Issue by NevaYue** [T1GxR/Axion-CS2-RAGE-CHEAT#2]

**Comment by Dufiw** [comment]
What do you mean?

**Comment by Dufiw** [comment]
It would just be sigs I believe. I can't seem to fix the injection crash yet so I can't really assist.

I know someone who has the full fixed source but says that source is private. Why? I have no clue why a pasted source would be private.

**Comment by NevaYue** [comment]
if the CS2 updated today or yesterday? i inject it yesterday.
![IMG_1184](https://github.com/T1GxR/Axion-CS2-RAGE-CHEAT/assets/102574946/877a210e-171c-4471-8ee9-01b2beb3f4df)

**Comment by Dufiw** [comment]
I believe it updated yesterday. Not 100% sure. 

I get too the part where it says '256' schema and then it crashes.

When debugging it shows the crash here
 `HashFixedDataInternal_t<tData>* GetNext()
{
    return *reinterpret_cast<HashFixedDataInternal_t<tData>**>(reinterpret_cast<std::uintptr_t>(this) + (0x20));
}`

**Comment by NevaYue** [comment]
soon

**Comment by NevaYue** [comment]
https://kip.lanzouq.com/b00b3k10jg
密码（pwd）:fw9i

**Comment by AMXBus** [comment]
> I believe it updated yesterday. Not 100% sure.
> 
> I get too the part where it says '256' schema and then it crashes.
> 
> When debugging it shows the crash here `HashFixedDataInternal_t<tData>* GetNext() { return *reinterpret_cast<HashFixedDataInternal_t<tData>**>(reinterpret_cast<std::uintptr_t>(this) + (0x20)); }`

Did you magage to fix it?

**Comment by NevaYue** [comment]
still work.just inject,not need update.17/04/2024 01:30 GMT+8

**Comment by AMXBus** [comment]
It doesn't after I build it from the source

**Comment by AMXBus** [comment]
extreme and xenos with multiple settings (no scrambling)

**Comment by Dufiw** [comment]
@AMXBus sadly no I haven't fixed yet

**Comment by MaYecha** [comment]
![image](https://github.com/T1GxR/Axion-CS2-RAGE-CHEAT/assets/145244567/5d1e2850-ec7c-4354-8768-87ec9c5741b2)

**Comment by MaYecha** [comment]
> maybe the question is your injector

我是基址获取有问题，不知道怎么回事

**Comment by NevaYue** [comment]
run as admin and add -allow_third_partsoftware

**Comment by MaYecha** [comment]
> run as admin and add -allow_third_partsoftware

do as follows,but still cannot get the offsets
debug control output:
[19-04-2024 17:43:45] [memory.cpp:370] [error] pattern not found: "48 89 5C 24 00 48 89 6C 24 00 56 57 41 56 48 81 EC 00 00 00 00 48 8D 0D"

**Comment by ImHereTyt** [comment]
**_`It's a very interesting situation.`_**

If you compile a new source code, the size of the dll will be: 3,631 KB. And if you download the new DLL, the size is already 7,492 KB. The source breaks the game and doesn't start. But the released dll works). It's very interesting that you added something that you didn't insert into the source code?))

> Mb virus?)

![image](https://github.com/T1GxR/Axion-CS2-RAGE-CHEAT/assets/167651436/d491a963-2e3e-4a89-8df6-ae735c29188b)

**Comment by T1GxR** [comment]
> **_`It's a very interesting situation.`_**
> 
> If you compile a new source code, the size of the dll will be: 3,631 KB. And if you download the new DLL, the size is already 7,492 KB. The source breaks the game and doesn't start. But the released dll works). It's very interesting that you added something that you didn't insert into the source code?))
> 
> > Mb virus?)
> 
> ![image](https://private-user-images.githubusercontent.com/167651436/324205808-d491a963-2e3e-4a89-8df6-ae735c29188b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NDgzNDYsIm5iZiI6MTcxMzY0ODA0NiwicGF0aCI6Ii8xNjc2NTE0MzYvMzI0MjA1ODA4LWQ0OTFhOTYzLTJlM2UtNGE4OS04ZGY2LWFlNzM1YzI5MTg4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQyMTIwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yzk5NjA3YmYwMzE0ZTJkZWQ0ZTg1NmY3MmU1NmE1ZjZlYTQyNDAxYTE5OTRmYjA4ZWJmYWFkZmNlZGJkNWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JvioYuAlrndnHH1OzjRJ6WfJ6Zbhn4pWCjCwUyAYoWw)

XD, did you successfully compiled the full sour

> **_`It's a very interesting situation.`_**
> 
> If you compile a new source code, the size of the dll will be: 3,631 KB. And if you download the new DLL, the size is already 7,492 KB. The source breaks the game and doesn't start. But the released dll works). It's very interesting that you added something that you didn't insert into the source code?))
> 
> > Mb virus?)
> 
> ![image](https://private-user-images.githubusercontent.com/167651436/324205808-d491a963-2e3e-4a89-8df6-ae735c29188b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NDgzNDYsIm5iZiI6MTcxMzY0ODA0NiwicGF0aCI6Ii8xNjc2NTE0MzYvMzI0MjA1ODA4LWQ0OTFhOTYzLTJlM2UtNGE4OS04ZGY2LWFlNzM1YzI5MTg4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQyMTIwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yzk5NjA3YmYwMzE0ZTJkZWQ0ZTg1NmY3MmU1NmE1ZjZlYTQyNDAxYTE5OTRmYjA4ZWJmYWFkZmNlZGJkNWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JvioYuAlrndnHH1OzjRJ6WfJ6Zbhn4pWCjCwUyAYoWw)

You tried to be smart but you failed, dumbass. For the cheat to work, you need to update all the signatures and schemas of the cheat. If you didn't even build the code completly, do not comment about it being a virus.  Being only 3600KB is the reason it doesn't start for you and keep crashing.

**Comment by ImHereTyt** [comment]
so the source code is lagging behind the latest version of the dll?'

> > **_`It's a very interesting situation.`_**
> > If you compile a new source code, the size of the dll will be: 3,631 KB. And if you download the new DLL, the size is already 7,492 KB. The source breaks the game and doesn't start. But the released dll works). It's very interesting that you added something that you didn't insert into the source code?))
> > > Mb virus?)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/167651436/324205808-d491a963-2e3e-4a89-8df6-ae735c29188b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NDgzNDYsIm5iZiI6MTcxMzY0ODA0NiwicGF0aCI6Ii8xNjc2NTE0MzYvMzI0MjA1ODA4LWQ0OTFhOTYzLTJlM2UtNGE4OS04ZGY2LWFlNzM1YzI5MTg4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQyMTIwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yzk5NjA3YmYwMzE0ZTJkZWQ0ZTg1NmY3MmU1NmE1ZjZlYTQyNDAxYTE5OTRmYjA4ZWJmYWFkZmNlZGJkNWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JvioYuAlrndnHH1OzjRJ6WfJ6Zbhn4pWCjCwUyAYoWw)
> 
> You tried to be smart but you failed, dumbass. For the cheat to work, you need to update all the signatures and schemas of the cheat. If you didn't even build the code completly, do not comment about it being a virus. Being only 3600KB is the reason it doesn't start for you and keep crashing.

**Comment by T1GxR** [comment]
> so the source code is lagging behind the latest version of the dll?'
> 
> > > **_`It's a very interesting situation.`_**
> > > If you compile a new source code, the size of the dll will be: 3,631 KB. And if you download the new DLL, the size is already 7,492 KB. The source breaks the game and doesn't start. But the released dll works). It's very interesting that you added something that you didn't insert into the source code?))
> > > > Mb virus?)
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/167651436/324205808-d491a963-2e3e-4a89-8df6-ae735c29188b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NDgzNDYsIm5iZiI6MTcxMzY0ODA0NiwicGF0aCI6Ii8xNjc2NTE0MzYvMzI0MjA1ODA4LWQ0OTFhOTYzLTJlM2UtNGE4OS04ZGY2LWFlNzM1YzI5MTg4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQyMTIwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yzk5NjA3YmYwMzE0ZTJkZWQ0ZTg1NmY3MmU1NmE1ZjZlYTQyNDAxYTE5OTRmYjA4ZWJmYWFkZmNlZGJkNWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JvioYuAlrndnHH1OzjRJ6WfJ6Zbhn4pWCjCwUyAYoWw)
> > 
> > 
> > You tried to be smart but you failed, dumbass. For the cheat to work, you need to update all the signatures and schemas of the cheat. If you didn't even build the code completly, do not comment about it being a virus. Being only 3600KB is the reason it doesn't start for you and keep crashing.

Not really, but I released the source code for coders to build their own cheats and get hooks and other requirements from this repository. (Basically as inspiration source)
I won't release the updated source code because I don't want to see 1:1 clones of this cheat everywhere on the internet.

**Comment by ImHereTyt** [comment]
Xd

> > so the source code is lagging behind the latest version of the dll?'
> > > > **_`It's a very interesting situation.`_**
> > > > If you compile a new source code, the size of the dll will be: 3,631 KB. And if you download the new DLL, the size is already 7,492 KB. The source breaks the game and doesn't start. But the released dll works). It's very interesting that you added something that you didn't insert into the source code?))
> > > > > Mb virus?)
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/167651436/324205808-d491a963-2e3e-4a89-8df6-ae735c29188b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NDgzNDYsIm5iZiI6MTcxMzY0ODA0NiwicGF0aCI6Ii8xNjc2NTE0MzYvMzI0MjA1ODA4LWQ0OTFhOTYzLTJlM2UtNGE4OS04ZGY2LWFlNzM1YzI5MTg4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQyMTIwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yzk5NjA3YmYwMzE0ZTJkZWQ0ZTg1NmY3MmU1NmE1ZjZlYTQyNDAxYTE5OTRmYjA4ZWJmYWFkZmNlZGJkNWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JvioYuAlrndnHH1OzjRJ6WfJ6Zbhn4pWCjCwUyAYoWw)
> > > 
> > > 
> > > You tried to be smart but you failed, dumbass. For the cheat to work, you need to update all the signatures and schemas of the cheat. If you didn't even build the code completly, do not comment about it being a virus. Being only 3600KB is the reason it doesn't start for you and keep crashing.
> 
> Not really, but I released the source code for coders to build their own cheats and get hooks and other requirements from this repository. (Basically as inspiration source) I won't release the updated source code because I don't want to see 1:1 clones of this cheat everywhere on the internet.

Xd
