### ISSUE TITLE
Insta banned lmao

### ISSUE THREAD

**Issue by Rofus06** [T1GxR/Axion-CS2-RAGE-CHEAT#4]
you recomend a injector cuz i used extrem injector and i got insta banned when i went into a real match and if it was not the injector then idk the dll is detect

**Comment by T1GxR** [comment]
I use exloader most of the times to load cheats because it has VAC bypass but you should use any injector with stealth Injection/VAC bypass. I used the cheat on a non prime account  for over 2 months of cheating and it's still not banned.

**Comment by Rofus06** [comment]
> I use exloader most of the times to load cheats because it has VAC bypass but you should use any injector with stealth Injection/VAC bypass. I used the cheat on a non prime account for over 2 months of cheating and it's still not banned.

ok i will try it (i used a prime account but it should not be a diff)

**Comment by T1GxR** [comment]
> > I use exloader most of the times to load cheats because it has VAC bypass but you should use any injector with stealth Injection/VAC bypass. I used the cheat on a non prime account for over 2 months of cheating and it's still not banned.
> 
> ok i will try it (i used a prime account but it should not be a diff)

You shouldn't use rage cheats on prime account because you will always get banned. Prime accounts are mainly targeted for vac bans.

**Comment by Rofus06** [comment]
> > > I use exloader most of the times to load cheats because it has VAC bypass but you should use any injector with stealth Injection/VAC bypass. I used the cheat on a non prime account for over 2 months of cheating and it's still not banned.
> > 
> > 
> > ok i will try it (i used a prime account but it should not be a diff)
> 
> You shouldn't use rage cheats on prime account because you will always get banned. Prime accounts are mainly targeted for vac bans.

i mean i see people spin botting and doing all crazy stuff and it has been 2 months and they are still not banned so i am not worried

**Comment by NevaYue** [comment]
noob,add -allow_thirdparty_software to steam.but this cheat just only a piece of shit,even cant against common people^ ^
